# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/designer/JurnalCreateForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import date
from JurnalController import JurnalController
from Jurnal import Jurnal
from custom import UIWindow


class Ui_NewJurnal(UIWindow):
    def setupUi(self, NewJurnal, controller: JurnalController):
        NewJurnal.setObjectName("NewJurnal")
        NewJurnal.resize(720, 480)
        NewJurnal.setStyleSheet("QPushButton {\n"
"    background: rgb(240, 240, 240);\n"
"    border: 2px solid rgb(130, 130, 130);\n"
"    border-width: 2px;\n"
"    border-radius: 0px;\n"
"    color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgb(215, 215, 215);\n"
"}\n"
"QPushButton:pressed {\n"
"    background: rgb(200, 200, 200);\n"
"}")
        self.JurnalEdit = QtWidgets.QTextEdit(NewJurnal)
        self.JurnalEdit.setGeometry(QtCore.QRect(60, 149, 600, 231))
        self.JurnalEdit.setObjectName("JurnalEdit")

        self.TitleEdit = QtWidgets.QLineEdit(NewJurnal)
        self.TitleEdit.setGeometry(QtCore.QRect(60, 90, 600, 41))
        font = QtGui.QFont()
        font.setFamily("HoloLens MDL2 Assets")
        font.setPointSize(20)
        self.TitleEdit.setFont(font)
        self.TitleEdit.setMaxLength(255)
        self.TitleEdit.setObjectName("TitleEdit")

        self.SubmitButton = QtWidgets.QPushButton(NewJurnal)
        self.SubmitButton.setGeometry(QtCore.QRect(470, 405, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SubmitButton.setFont(font)
        self.SubmitButton.setObjectName("SubmitButton")
        self.SubmitButton.clicked.connect(self.submit)

        self.CancelButton = QtWidgets.QPushButton(NewJurnal)
        self.CancelButton.setGeometry(QtCore.QRect(260, 405, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CancelButton.setFont(font)
        self.CancelButton.setObjectName("CancelButton")
        self.CancelButton.clicked.connect(self.close)

        self.label = QtWidgets.QLabel(NewJurnal)
        self.label.setGeometry(QtCore.QRect(60, 30, 600, 31))
        font = QtGui.QFont()
        font.setFamily("HoloLens MDL2 Assets")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.controller = controller

        self.retranslateUi(NewJurnal)
        QtCore.QMetaObject.connectSlotsByName(NewJurnal)

    def retranslateUi(self, NewJurnal):
        _translate = QtCore.QCoreApplication.translate
        NewJurnal.setWindowTitle(_translate("NewJurnal", "Form"))
        self.TitleEdit.setPlaceholderText(_translate("NewJurnal", "Title"))
        self.SubmitButton.setText(_translate("NewJurnal", "Submit"))
        self.CancelButton.setText(_translate("NewJurnal", "Cancel"))
        self.label.setText(_translate("NewJurnal", 
                                      "Jurnal Harianku ({0})".format(date.today().strftime('%d-%m-%Y'))))
        
    def setReadOnly(self, jurnal: Jurnal):
        # Fill and disable all edit text
        self.TitleEdit.setText(jurnal.judul)
        self.JurnalEdit.setText(jurnal.isi)
        self.TitleEdit.setReadOnly(True)
        self.JurnalEdit.setReadOnly(True)
        
        # Remove submit button
        self.SubmitButton.setVisible(False)
        
        # change cancel button -> back
        self.CancelButton.setGeometry(QtCore.QRect(470, 405, 190, 40))
        self.CancelButton.setText('Back')

    def submit(self):
        # Insert to db
        # Show success/fail message
        msg = QtWidgets.QMessageBox()
        try:
            self.controller.addJurnal(self.TitleEdit.text(), self.JurnalEdit.toPlainText())
            msg.setWindowTitle("Berhasil!")
            msg.setText("Jurnal berhasil ditambahkan ke db")
            msg.setIcon(QtWidgets.QMessageBox.Information)
            msg.exec_()
        except Exception as e:
            msg.setWindowTitle("Terjadi kesalahan!")
            msg.setText(str(e))
            msg.setIcon(QtWidgets.QMessageBox.Critical)
            msg.exec_()

        # TODO Return to Jurnal UI

    def close(self):
        # Return to Jurnal UI
        pass

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewJurnal = QtWidgets.QWidget()
    ui = Ui_NewJurnal()
    ui.setupUi(NewJurnal, JurnalController())
    NewJurnal.show()
    sys.exit(app.exec_())
