# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RiwayatTidurUserInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from custom import *
import Jurnal as Jurnal
from JurnalController import JurnalController
#TODO: Controller
from os import path
import sys

class SleepOverlay(CustomOverlay):
    #TODO: Overlay
    def __init__(self, codeIdx, controller, parent=None):
        super(SleepOverlay, self).__init__(parent)
        self.controller = controller
        self.codeIdx = codeIdx
    
        self.block = QFrame(self)
        self.block.setFrameShape(QFrame.StyledPanel)
        self.block.setStyleSheet(
                                "background-color: rgb(255, 255, 255);"
                                "border-width: 2;"
                                "border-style: solid;"
                                )
        self.block.move(300, 100)
        self.block.resize(600, 480)

        font = QFont()
        font.setFamily("Helvetica")
        font.setPointSize(13)

        self.titleLabel = QLabel("Judul: ", self.block)
        self.titleLabel.setStyleSheet("border-width: 0;")
        self.titleLabel.move(10,15)
        self.titleLabel.setContentsMargins(5, 0, 0, 0)
        self.titleLabel.setFont(font)
        
        self.titleInput = QLineEdit(self.block)
        self.titleInput.setGeometry(10,45, 580, 40)
        self.titleInput.setContentsMargins(5, 0, 0, 0)
        self.titleInput.setFont(font)

        self.titleLabel = QLabel("Isi: ", self.block)
        self.titleLabel.setStyleSheet("border-width: 0;")
        self.titleLabel.move(10, 105)
        self.titleLabel.setContentsMargins(5, 0, 0, 0)
        self.titleLabel.setFont(font)
        
        self.jurnalInput = QTextEdit(self.block)
        self.jurnalInput.setGeometry(15,135, 575, 290)
        self.jurnalInput.setContentsMargins(5, 0, 0, 0)
        self.jurnalInput.setFont(font)

        if (codeIdx != 0):
            rows = self.controller.daftarJurnal
            self.titleInput.setText(rows[codeIdx - 1].judul)
            self.jurnalInput.setText(rows[codeIdx - 1].isi)
            self.titleInput.setReadOnly(True)
            self.jurnalInput.setReadOnly(True)

        self.closeButton = CustomSVGButton(path.join(self.resources, "cancelIcon.svg"), path.join(self.resources, "cancelIconH.svg"), self.block)
        self.closeButton.setGeometry(QRect(525, 434, 23, 23))
        self.closeButton.setObjectName("CloseButton")
        self.closeButton.clicked.connect(self._onclose)

        self.confirmButton = CustomSVGButton(path.join(self.resources, "confirmIcon.svg"), path.join(self.resources, "confirmIconH.svg"), self.block)
        self.confirmButton.setGeometry(QRect(565, 434, 23, 23))
        self.confirmButton.setObjectName("ConfirmButton")
        self.confirmButton.clicked.connect(self._onconfirm)

    def _onconfirm(self):
        if(self.codeIdx == 0):
            self.signals.confirm.emit(self.codeIdx)
        else:
            self.signals.close.emit()

class SleepForm(UIWindow):
    def setupUi(self, Form):
        self.controller = JurnalController()

        self.parent = Form
        self.entries = 1
        self.mode = "List"

        Form.setObjectName("FormSleep")
        Form.resize(1280, 786)
        
        self.horizontalLayout = QHBoxLayout(Form)
        self.horizontalLayout.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.OpeningPanel = QFrame(Form)
        self.OpeningPanel.setObjectName("OpeningPanel")
        self.OpeningPanel.setStyleSheet(
"QFrame#OpeningPanel {\n"
"    background: rgb(255, 255, 255);\n"
"    border: 1px solid rgb(130, 130, 130);\n"
"    border-radius: 0px;\n"
"}"
"QPushButton {\n"
"    background: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(130, 130, 130);\n"
"    border-width: 2px;\n"
"    border-radius: 0px;\n"
"    color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgb(215, 215, 215);\n"
"}\n"
"QPushButton:pressed {\n"
"    background: rgb(200, 200, 200);\n"
"}")
        
        font = QFont()
        font.setFamily("Helvetica")
        font.setPointSize(22)

        
        self.SleepTitle = QLabel(self.OpeningPanel)
        self.SleepTitle.setGeometry(QRect(30, 64, 240, 35))
        self.SleepTitle.setFont(font)
        self.SleepTitle.setObjectName("SleepTitle")
        self.SleepTitle.setAlignment(Qt.AlignLeft|Qt.AlignTop)

        font.setPointSize(13)
    
        self.SleepSubtitle = QLabel(self.OpeningPanel)
        self.SleepSubtitle.setGeometry(QRect(30, 128, 240, 40))
        self.SleepSubtitle.setFont(font)
        self.SleepSubtitle.setWordWrap(True)
        self.SleepSubtitle.setObjectName("SleepSubtitle")
        self.SleepSubtitle.setAlignment(Qt.AlignLeft|Qt.AlignTop)

        self.ReturnButton = QPushButton(self.OpeningPanel)
        self.ReturnButton.setGeometry(QRect(30, 650, 190, 40))
        self.ReturnButton.setFont(font)
        self.ReturnButton.setAutoFillBackground(False)
        self.ReturnButton.setStyleSheet("text-align: left;\n"
                                      "padding: 5px;\n")
        self.ReturnButton.setCheckable(False)
        self.ReturnButton.setChecked(False)
        self.ReturnButton.setAutoDefault(False)
        self.ReturnButton.setDefault(False)
        self.ReturnButton.setFlat(False)
        self.ReturnButton.setObjectName("ReturnButton")
        self.ReturnButton.clicked.connect(lambda: self._onswitch("Home"))

        self.StatisticsButton = QPushButton(self.OpeningPanel)
        self.StatisticsButton.setGeometry(QRect(30, 600, 190, 40))
        self.StatisticsButton.setFont(font)
        self.StatisticsButton.setStyleSheet("text-align: left;\n"
                                           "padding: 5px;\n")
        self.StatisticsButton.setCheckable(False)
        self.StatisticsButton.setChecked(False)
        self.StatisticsButton.setAutoDefault(False)
        self.StatisticsButton.setDefault(False)
        self.StatisticsButton.setFlat(False)
        self.StatisticsButton.setObjectName("StatisticsButton")
        self.StatisticsButton.clicked.connect(self._onStatistics)
        
        
        self.content = QFrame()
        self.content.setContentsMargins(40, 64, 20, -1)
        self.content.setObjectName("content")
        self.content.setStyleSheet(
"QFrame#content {\n"
"    background: rgb(200, 200, 200);\n"
"    border: 1px solid rgb(130, 130, 130);\n"
"    border-radius: 0px;\n"
"}\n"
"QPushButton {\n"
"    background: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(130, 130, 130);\n"
"    border-width: 2px;\n"
"    border-radius: 0px;\n"
"    color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgb(215, 215, 215);\n"
"}\n"
"QPushButton:pressed {\n"
"    background: rgb(200, 200, 200);\n"
"}")
        
        self.scrollArea = QScrollArea(self.content)
        self.scrollAreaHeight = 70
        self.scrollArea.setGeometry(QRect(30, 30, 890, self.scrollAreaHeight))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollArea.setStyleSheet(
"QWidget {\n"
"    background: rgb(200, 200, 200);\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: 1px solid rgb(130, 130, 130);\n"
"    background: rgb(255, 255, 255);\n"
"    width: 10px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(130, 130, 130);\n"
"    min-height: 0px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    border: 1px solid rgb(130, 130, 130);\n"
"    background: rgb(255, 255, 255);\n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    border: 1px solid rgb(130, 130, 130);\n"
"    background: rgb(255, 255, 255);\n"
"    height: 0 px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
"}"

"QPushButton {\n"
"    background: rgb(255, 255, 255);\n"
"    border: 1px solid rgb(130, 130, 130);\n"
"    padding-left: 10px;\n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
"    min-height: 50px;\n"
"    text-align: left;\n"
"\n"
"    margin-left: 20px;\n"
"    margin-right: 30px;\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgb(215, 215, 215);\n"
"}\n"
"QPushButton:pressed {\n"
"    background: rgb(200, 200, 200);\n"
"}\n"
"")
        self.listWrapper = QWidget()
        self.listWrapper.setGeometry(QRect(0, 0, 960, 786))
        
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWrapper.sizePolicy().hasHeightForWidth())

        self.listWrapper.setSizePolicy(sizePolicy)

        self.list = QVBoxLayout(self.listWrapper)
        self.list.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.list.setObjectName("list")

        self.addButton = QPushButton(self.content)
        self.addButton.setObjectName("pushButton")
        self.addButton.setFont(font)
        self.addButton.clicked.connect(lambda: self._onpopup(0))

        self.list.addWidget(self.addButton)

        self.scrollArea.setWidget(self.listWrapper)

        self.horizontalLayout.addWidget(self.OpeningPanel)
        self.horizontalLayout.addWidget(self.content)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)


        self.statistics = QFrame(Form)
        self.statistics.setContentsMargins(40, 64, 20, -1)
        self.statistics.setObjectName("statistics")
        self.statistics.setStyleSheet(
"QFrame#statistics {\n"
"    background: rgb(200, 200, 200);\n"
"    border: 1px solid rgb(130, 130, 130);\n"
"    border-radius: 0px;\n"
"}\n"
"QPushButton {\n"
"    background: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(130, 130, 130);\n"
"    border-width: 2px;\n"
"    border-radius: 0px;\n"
"    color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgb(215, 215, 215);\n"
"}\n"
"QPushButton:pressed {\n"
"    background: rgb(200, 200, 200);\n"
"}")

        self.statsAvg = QLabel(self.statistics)
        self.statsAvg.setGeometry(QRect(30, 160, 321, 61))
        self.statsAvg.setFont(font)
        self.statsAvg.setFrameShape(QFrame.NoFrame)
        self.statsAvg.setFrameShadow(QFrame.Plain)
        self.statsAvg.setObjectName("label")
        self.label_1 = QLabel(self.statistics)
        self.label_1.setGeometry(QRect(30, 230, 60, 40))
        self.label_1.setLayoutDirection(Qt.LeftToRight)
        self.label_1.setFrameShape(QFrame.StyledPanel)
        self.label_1.setAlignment(Qt.AlignCenter)
        self.label_1.setObjectName("label_2")
        self.label_1.setStyleSheet(
"    background: rgb(255, 255, 255);\n"
)
        self.label_2 = QLabel(self.statistics)
        self.label_2.setGeometry(QRect(30, 290, 60, 40))
        self.label_2.setLayoutDirection(Qt.LeftToRight)
        self.label_2.setFrameShape(QFrame.StyledPanel)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_2.setObjectName("label_5")
        self.label_2.setStyleSheet(
"    background: rgb(255, 255, 255);\n"
)
        self.label_3 = QLabel(self.statistics)
        self.label_3.setGeometry(QRect(30, 350, 60, 40))
        self.label_3.setLayoutDirection(Qt.LeftToRight)
        self.label_3.setFrameShape(QFrame.StyledPanel)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_3.setObjectName("label_6")
        self.label_3.setStyleSheet(
"    background: rgb(255, 255, 255);\n"
)
        self.label_4 = QLabel(self.statistics)
        self.label_4.setGeometry(QRect(30, 410, 60, 40))
        self.label_4.setLayoutDirection(Qt.LeftToRight)
        self.label_4.setFrameShape(QFrame.StyledPanel)
        self.label_4.setAlignment(Qt.AlignCenter)
        self.label_4.setObjectName("label_7")
        self.label_4.setStyleSheet(
"    background: rgb(255, 255, 255);\n"
)
        self.label_5 = QLabel(self.statistics)
        self.label_5.setGeometry(QRect(30, 470, 60, 40))
        self.label_5.setLayoutDirection(Qt.LeftToRight)
        self.label_5.setFrameShape(QFrame.StyledPanel)
        self.label_5.setAlignment(Qt.AlignCenter)
        self.label_5.setObjectName("label_8")
        self.label_5.setStyleSheet(
"    background: rgb(255, 255, 255);\n"
)
        self.label_6 = QLabel(self.statistics)
        self.label_6.setGeometry(QRect(30, 530, 60, 40))
        self.label_6.setLayoutDirection(Qt.LeftToRight)
        self.label_6.setFrameShape(QFrame.StyledPanel)
        self.label_6.setAlignment(Qt.AlignCenter)
        self.label_6.setObjectName("label_9")
        self.label_6.setStyleSheet(
"    background: rgb(255, 255, 255);\n"
)
        self.label_7 = QLabel(self.statistics)
        self.label_7.setGeometry(QRect(30, 590, 60, 40))
        self.label_7.setLayoutDirection(Qt.LeftToRight)
        self.label_7.setFrameShape(QFrame.StyledPanel)
        self.label_7.setAlignment(Qt.AlignCenter)
        self.label_7.setObjectName("label_10")
        self.label_7.setStyleSheet(
"    background: rgb(255, 255, 255);\n"
)
        self.progressBar_1 = QProgressBar(self.statistics)
        self.progressBar_1.setGeometry(QRect(110, 240, 800, 20))
        self.progressBar_1.setMaximum(2400)
        self.progressBar_1.setProperty("value", 439)
        self.progressBar_1.setObjectName("progressBar")
        self.progressBar_2 = QProgressBar(self.statistics)
        self.progressBar_2.setGeometry(QRect(110, 300, 800, 20))
        self.progressBar_2.setMaximum(2400)
        self.progressBar_2.setProperty("value", 659)
        self.progressBar_2.setObjectName("progressBar_2")
        self.progressBar_3 = QProgressBar(self.statistics)
        self.progressBar_3.setGeometry(QRect(110, 360, 800, 20))
        self.progressBar_3.setMaximum(2400)
        self.progressBar_3.setProperty("value", 420)
        self.progressBar_3.setObjectName("progressBar_3")
        self.progressBar_4 = QProgressBar(self.statistics)
        self.progressBar_4.setGeometry(QRect(110, 420, 800, 20))
        self.progressBar_4.setMaximum(2400)
        self.progressBar_4.setProperty("value", 429)
        self.progressBar_4.setObjectName("progressBar_4")
        self.progressBar_5 = QProgressBar(self.statistics)
        self.progressBar_5.setGeometry(QRect(110, 480, 800, 20))
        self.progressBar_5.setMaximum(2400)
        self.progressBar_5.setProperty("value", 310)
        self.progressBar_5.setObjectName("progressBar_5")
        self.progressBar_6 = QProgressBar(self.statistics)
        self.progressBar_6.setGeometry(QRect(110, 540, 800, 20))
        self.progressBar_6.setMaximum(2400)
        self.progressBar_6.setProperty("value", 549)
        self.progressBar_6.setObjectName("progressBar_6")
        self.progressBar_7 = QProgressBar(self.statistics)
        self.progressBar_7.setGeometry(QRect(110, 600, 800, 20))
        self.progressBar_7.setMaximum(2400)
        self.progressBar_7.setProperty("value", 422)
        self.progressBar_7.setObjectName("progressBar_7")
        self.statistics.hide()

        self.retranslateUi(Form)
        #TODO: get statistics
        QMetaObject.connectSlotsByName(Form)

    def addJurnal(self, jurnal: Jurnal.Jurnal):
        #TODO: sleep data
        _translate = QCoreApplication.translate
        font = QFont()
        font.setFamily("Helvetica")
        font.setPointSize(13)

        exec("self.entry%d = QPushButton(self.content)" % self.entries)
        exec("self.entry%d.setObjectName('entry%d')" % (self.entries, self.entries))
        exec("self.list.insertWidget(1, self.entry%d)" % self.entries)
        exec("self.entry%d.setText(_translate('Form', '     %s | %s'))" % (self.entries, jurnal.waktuEdit, jurnal.judul))
        exec("self.entry%d.clicked.connect(lambda: self._onpopup(%d))" % (self.entries, self.entries), locals())
        exec("self.entry%d.setFont(font)" % self.entries)

        self.entries += 1
        self.scrollAreaHeight = min(726, self.entries * 70)
        self.scrollArea.setGeometry(QRect(30, 30, 890, self.scrollAreaHeight))

    def retranslateUi(self, Form):
        _translate = QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.SleepSubtitle.setText(_translate("Form", "Seberapa lama kamu tidur hari ini?"))
        self.SleepTitle.setText(_translate("Form", "Riwayat Tidur"))
        self.ReturnButton.setText(_translate("Form", "Kembali"))
        self.StatisticsButton.setText(_translate("Form", "Statistik"))
        self.addButton.setText(_translate("Form", "     +          Tambah Riwayat Tidur Baru"))
        self.statsAvg.setText(_translate("Form", "Rata - rata tidur: 5.39 jam"))
        self.label_1.setText(_translate("Form", "Sun"))
        self.label_2.setText(_translate("Form", "Sat"))
        self.label_3.setText(_translate("Form", "Fri"))
        self.label_4.setText(_translate("Form", "Thu"))
        self.label_5.setText(_translate("Form", "Wed"))
        self.label_6.setText(_translate("Form", "Tue"))
        self.label_7.setText(_translate("Form", "Mon"))
        self.progressBar_1.setFormat(_translate("Form", "%p%"))
        self.progressBar_2.setFormat(_translate("Form", "%p%"))
        self.progressBar_3.setFormat(_translate("Form", "%p%"))
        self.progressBar_4.setFormat(_translate("Form", "%p%"))
        self.progressBar_5.setFormat(_translate("Form", "%p%"))
        self.progressBar_6.setFormat(_translate("Form", "%p%"))

    def _onStatistics(self):
        if self.mode == "List":
            self.mode = "Statistic"
            self.horizontalLayout.replaceWidget(self.content, self.statistics)
            self.content.hide()
            self.statistics.show()
        else:
            self.mode = "List"
            self.horizontalLayout.replaceWidget(self.statistics, self.content)
            self.statistics.hide()
            self.content.show()

    def _onpopup(self, codeIdx):
        self.popup = SleepOverlay(codeIdx, self.controller, self.parent)
        self.popup.move(0, 0)
        self.popup.resize(self.parent.width(), self.parent.height())
        self.popup.signals.close.connect(self._closepopup)
        self.popup.signals.confirm.connect(self._onconfirm)
        self.popup.codeIdx = codeIdx
        self.popup.show()

    def _closepopup(self):
        self.popup.close()

    def _onconfirm(self):
        #TODO: Sleep Data
        self.popup.close()
        
if __name__ == "__main__":
    app = QApplication(sys.argv)
    Form = QWidget()
    ui = SleepForm()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
